<script setup lang="ts">
import type { MigratedConfigsByScenario, MigrationScenario } from '~~/shared/types'
import { useClipboard } from '@vueuse/core'
import { computed, ref } from 'vue'

const props = defineProps<{
  configs: MigratedConfigsByScenario
  scenarioCommands: Record<MigrationScenario, string>
  disabled?: boolean
  modelValue?: MigrationScenario
}>()
const emit = defineEmits<{
  'update:modelValue': [value: MigrationScenario]
}>()

const { copy } = useClipboard()
const fallbackScenario = ref<MigrationScenario>('default')

const activeScenario = computed({
  get() {
    return props.modelValue ?? fallbackScenario.value
  },
  set(value: MigrationScenario) {
    fallbackScenario.value = value
    emit('update:modelValue', value)
  },
})

const scenarioOrder: Array<{ value: MigrationScenario, label: string }> = [
  { value: 'native', label: 'Native' },
  { value: 'default', label: 'Default' },
  { value: 'max', label: 'Max' },
]

const activeCode = computed(() => {
  return props.configs[activeScenario.value]?.code ?? '{}'
})

const activeCommand = computed(() => {
  return props.scenarioCommands[activeScenario.value] ?? ''
})
</script>

<template>
  <div border="~ base rounded" mb4 p3>
    <div mb3>
      <div text-sm font-semibold>
        Migrated Oxlint Config
      </div>
    </div>

    <div mb3 flex="~ gap-2 wrap">
      <button
        v-for="scenario of scenarioOrder"
        :key="scenario.value"
        btn-action px3 py1 text-sm
        :class="activeScenario === scenario.value ? 'btn-action-active' : 'op70'"
        @click="activeScenario = scenario.value"
      >
        {{ scenario.label }}
      </button>
    </div>

    <div border="~ none rounded" mb3 bg-code p2 flex="~ gap-2 items-center">
      <code flex-auto of-auto text-sm>{{ activeCommand }}</code>
      <button
        btn-action-sm
        :class="props.disabled ? 'op50 cursor-not-allowed' : ''"
        :disabled="props.disabled"
        @click="copy(activeCommand)"
      >
        Copy
      </button>
    </div>

    <div mb2 text-xs op60>
      Generated by @oxlint/migrate (simulation config-level).
    </div>

    <div relative>
      <div absolute right-2 top-2 z-1>
        <button
          btn-action-sm
          :class="props.disabled ? 'op50 cursor-not-allowed' : ''"
          :disabled="props.disabled"
          @click="copy(activeCode)"
        >
          Copy
        </button>
      </div>
      <Shiki
        lang="json"
        :code="activeCode"
        of-auto rounded bg-code p2 text-sm
      />
    </div>
  </div>
</template>
